<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>MulliganPlugin</AssemblyName>
    <RootNamespace>HstMulligan.Plugin</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MulliganCore\MulliganCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HearthstoneDeckTracker">
      <HintPath>$(HdtLibDir)HearthstoneDeckTracker.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HearthDb">
      <HintPath>$(HdtLibDir)HearthDb.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HearthMirror">
      <HintPath>$(HdtLibDir)HearthMirror.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
